#Zizhao Li (1267416) zizhaol2@student.unimelb.edu.au (Suzhou, China)
#Fu Zhu (1166186) fuzhu@student.unimelb.edu.au (Melbourne, Australia)
#Chuting Wang (1074511) chutingw@student.unimelb.edu.au (Xi’an, China)
#Xuezhu Wu (938808) xuezhuw@student.unimelb.edu.au (Hangzhou, China)
#Yuepeng Sheng (1048382) yuepengs@student.unimelb.edu.au (Shanghai, China)

# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: shared

volumes:
  - vol_name: demo-vol-1
    vol_size: 50
    device: /dev/vdb
    mountpoint: /data
  - vol_name: demo-vol-2
    vol_size: 50
    device: /dev/vdb
    mountpoint: /data
  - vol_name: demo-vol-3
    vol_size: 50
    device: /dev/vdb
    mountpoint: /data
  - vol_name: demo-vol-4
    vol_size: 50
    device: /dev/vdb
    mountpoint: /home/ubuntu/COMP90024

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: outside_couch
    description: "security group for couch"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: proxy
    description: "proxy"
    protocol: tcp
    port_range_min: 8000
    port_range_max: 8000
    remote_ip_prefix: 0.0.0.0/0
  - name: inter_cluster_communication
    description: "cluster communication"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0
  - name: inter_cluster_communication
    description: "cluster communication"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: inter_cluster_communication
    description: "cluster communication"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: demo-1
    volumes: ['demo-vol-1']
    flavor: uom.mse.2c9g
  - name: demo-2
    volumes: ['demo-vol-2']
    flavor: uom.mse.2c9g
  - name: demo-3
    volumes: ['demo-vol-3']
    flavor: uom.mse.2c9g
  - name: demo-4
    volumes: ['demo-vol-4']
    flavor: uom.mse.2c9g
    

couchdb_user: admin
couchdb_password: password
couchdb_version: '3.0.0'
masternode: '172.26.130.194'
dbnodes: ['172.26.129.30','172.26.134.49']
couchdb_port: 5984

