#Zizhao Li (1267416) zizhaol2@student.unimelb.edu.au (Suzhou, China)
#Fu Zhu (1166186) fuzhu@student.unimelb.edu.au (Melbourne, Australia)
#Chuting Wang (1074511) chutingw@student.unimelb.edu.au (Xi’an, China)
#Xuezhu Wu (938808) xuezhuw@student.unimelb.edu.au (Hangzhou, China)
#Yuepeng Sheng (1048382) yuepengs@student.unimelb.edu.au (Shanghai, China)

- name: get and start couchdb
  become: yes
  docker_container:
    name: couchdb
    image: "ibmcom/couchdb3:{{ couchdb_version }}"
    state: started
    ports:
      - "5984:5984"
      - "9100-9200:9100-9200"
      - "4369:4369"
    volumes:
      - /data
    pull: yes
    env:
      COUCHDB_USER: "{{couchdb_user}}"
      COUCHDB_PASSWORD: "{{couchdb_password}}"
      NODENAME: "{{ansible_host}}"
